version: 2
jobs:
  build:
    docker:
      - image: "circleci/python:2.7.13"
    steps:
      - run:
          command: |
            pip install nose --user
            cd ~/algorithms
            nosetests
    working_directory: ~/algorithms