version: 2
jobs:
  build:
    docker:
      - image: "circleci/python:2.7.13"
    steps:
      - checkout
      - run:
          - pip install requirements
  test:
    docker:
      - image: circleci/php:7.1.9
    steps:
      - checkout
      - run:
          nosetests .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test